# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 125bdf6a23b3e345dc62dea6288ff110e24add48c4527a8a5463ef533e7fab2086d176f5c98040b44990d22a6d9b90176a9c62de881f55aab1d7e3b051a7bf5f

test:
  secret_key_base: f74b17f24c1647d74f2e130d5f5e0e74e05f1d92c1fddd7d8ff3fd4d00524dedc77b536f4b167fa5219fcbb98aaac388cd4f1daf349258419a87cee8ccac4f88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
